name: Continuous Staging

on:
  workflow_run:
    workflows: ["Continuous Delivery"]
    types: [completed]

env:
  REGISTRY: ghcr.io
  FLASK_IMAGE_NAME: ${{ github.repository }}/serving
  MLFLOW_TRACKING_URI: http://dsn2026hotcrp.dei.uc.pt:8080
  MLFLOW_EXPERIMENT_NAME: iris_test_jrc
  MLFLOW_MODEL_NAME: iris_model_name

jobs:

  stage-tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.13' }
      - run: pip install uv

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: docker pull ${{ env.REGISTRY }}/${{ github.repository }}/serving:staging

      - name: Run staging container
        run: |
          docker run -d --name serving-app -p 8080:8080 \
          ${{ env.REGISTRY }}/${{ github.repository }}/serving:staging
          sleep 10

      - run: uv run pytest tests/test_e2e.py -v
      - run: docker stop serving-app || true
      - run: docker rm serving-app || true

      - name: Promote to prod alias
        env:
          MLFLOW_TRACKING_URI: ${{ env.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_PASSWORD }}
          FROM_ALIAS: staging
          TO_ALIAS: production
        run: uv run python model-promotion/promote_model.py

      - name: Push prod container tag
        run: |
          docker tag ${{ env.REGISTRY }}/${{ github.repository }}/serving:staging \
                     ${{ env.REGISTRY }}/${{ github.repository }}/serving:production
          docker push ${{ env.REGISTRY }}/${{ github.repository }}/serving:production